apiVersion: v1
kind: Service
metadata:
  name: aegis
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: aegis
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.proxyNodePort }}
      nodePort: {{ .Values.service.proxyNodePort }}
      {{- end }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.metricsNodePort }}
      nodePort: {{ .Values.service.metricsNodePort }}
      {{- end }}
